version: "3.9"
services:
  backend:
    container_name: dev-camper-backend
    stop_grace_period: 1m
    build:
      target: ${BACKEND_TARGET}
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app:ro
    healthcheck:
      test: curl --fail http://localhost:${BACKEND_PORT}/health || exit 1
      start_period: 5s
      interval: 3s
      timeout: 10s
      retries: 3
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: dev-camper-database
    image: mongo:6.0.7
    restart: unless-stopped
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    ports:
      - ${DATABASE_PORT}:27017
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      start_period: 5s
      interval: 3s
      timeout: 10s
      retries: 3
volumes:
  data:
