version: "3.8"
services:
  backend:
    stop_grace_period: 1m # how much time docker gives container for shutting down with SIGINT and SIGTERM signals before it force kills it
    container_name: backend
    build:
      target: ${BACKEND_TARGET}
      context: ./
      dockerfile: Dockerfile
    env_file: 
     - ./env/backend.env
    environment:
      # pass env variables from: '.env' docker-compose config file to the container
      - PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app:ro
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: database
    restart: always # automatically restart container after it crashes
    image: mongo:5.0.8
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    ports:
      - ${DATABASE_PORT}:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 5s
      retries: 3
      start_period: 3s
volumes:
  data:
